#This file is an example of an environment file for defining the isolated
#networks and related parameters.
resource_registry:
  # Network Interface templates to use (these files must exist)
  # OS::TripleO::BlockStorage::Net::SoftwareConfig: ../network/config/single-nic-vlans/cinder-storage.yaml
  OS::TripleO::Compute::Net::SoftwareConfig: /home/stack/templates/compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: /home/stack/templates/controller.yaml
  # OS::TripleO::ObjectStorage::Net::SoftwareConfig: ../network/config/single-nic-vlans/swift-storage.yaml
  # OS::TripleO::CephStorage::Net::SoftwareConfig: ../network/config/single-nic-vlans/ceph-storage.yaml

parameter_defaults:
  # This section is where deployment-specific configuration is done
  # CIDR subnet mask length for provisioning network
  ControlPlaneSubnetCidr: '24'
  # Gateway router for the provisioning network (or Undercloud IP)
  ControlPlaneDefaultRoute: 192.0.2.1
  EC2MetadataIp: 192.0.2.1  # Generally the IP of the Undercloud
  # Customize the IP subnets to match the local environment
  InternalApiNetCidr: 10.0.30.0/24
  StorageNetCidr: 10.0.20.0/24
  StorageMgmtNetCidr: 10.0.40.0/24
  TenantNetCidr: 10.0.50.0/24
  ExternalNetCidr: 10.0.10.0/24
  # Customize the VLAN IDs to match the local environment
  InternalApiNetworkVlanID: 30
  StorageNetworkVlanID: 20
  StorageMgmtNetworkVlanID: 40
  TenantNetworkVlanID: 50
  ExternalNetworkVlanID: 10
  # Customize the IP ranges on each network to use for static IPs and VIPs
  InternalApiAllocationPools: [{'start': '10.0.30.10', 'end': '10.0.30.100'}]
  StorageAllocationPools: [{'start': '10.0.20.10', 'end': '10.0.20.100'}]
  StorageMgmtAllocationPools: [{'start': '10.0.40.10', 'end': '10.0.40.100'}]
  TenantAllocationPools: [{'start': '10.0.50.10', 'end': '10.0.50.100'}]
  # Leave room if the external network is also used for floating IPs
  ExternalAllocationPools: [{'start': '10.0.10.10', 'end': '10.0.10.100'}]
  # Gateway router for the external network
  ExternalInterfaceDefaultRoute: 10.0.10.254
  # Uncomment if using the Management Network (see network-management.yaml)
  # ManagementNetCidr: 10.0.1.0/24
  # ManagementAllocationPools: [{'start': '10.0.1.10', 'end', '10.0.1.50'}]
  # Use either this parameter or ControlPlaneDefaultRoute in the NIC templates
  # ManagementInterfaceDefaultRoute: 10.0.1.1
  # Define the DNS servers (maximum 2) for the overcloud nodes
  DnsServers: ["8.8.8.8","8.8.4.4"]
  # Set to empty string to enable multiple external networks or VLANs
  NeutronExternalNetworkBridge: "''"
  # The tunnel type for the tenant network (vxlan or gre). Set to '' to disable tunneling.
  NeutronTunnelTypes: 'vxlan'
  # Customize bonding options, e.g. "mode=4 lacp_rate=1 updelay=1000 miimon=100"
  # BondInterfaceOvsOptions: "bond_mode=active-backup"
  NeutronFlatNetworks: 'provider'
  OpenDaylightProviderMappings: 'provider:br-provider'
